import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], style: "normal", weight: "400" });

export const metadata = {
  title: "Netflix Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="overflow-hidden cursor-none"
    >
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
